### ISSUE TITLE
Uncaught UPNP cleanup error during exit

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/wireguard-go#47]
As seen on @jgoimard's environment:
```
dial tcp 127.0.0.1:6970: connect: connection refused"
^Cquit called in 120791
INFO: (wg0) 2021/01/27 11:34:15 Device closing
Master process is exiting
Tray is exiting
Cleaning up environment file: /home/jeremy/.wgenv-1611764865
jeremy@jeremy-XPS:~/Documents/git/wireguard-go/amd64$ INFO: (wg0) 2021/01/27 11:34:15 Interface closed
quit called in 120807
Parent process is dead, exiting
quit called in 120807
Recoved panic in program: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x5b, 0x0, 0x0)
    /home/jeremy/Documents/git/wireguard-go/.deps/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
    /home/jeremy/Documents/git/wireguard-go/.deps/go/src/runtime/debug/stack.go:16 +0x25
github.com/inverse-inc/wireguard-go/binutils.CapturePanic()
    /home/jeremy/Documents/git/wireguard-go/binutils/binutils.go:42 +0xb4
panic(0x1039440, 0x493a020)
    /home/jeremy/Documents/git/wireguard-go/.deps/go/src/runtime/panic.go:969 +0x175
github.com/inverse-inc/upnp.(*GetListOfPortMappings).buildRequest(0xc000e6ba28, 0x114938b, 0x3, 0x0)
    /home/jeremy/go/pkg/mod/github.com/inverse-inc/upnp@v0.0.0-20201222212413-bcc73e2a6122/GetListOfPortMappings.go:64 +0xd46
github.com/inverse-inc/upnp.(*GetListOfPortMappings).Send(0xc000e6ba28, 0x114938b, 0x3, 0x4954b20, 0xc000e6ba00, 0x4ec7a5)
    /home/jeremy/go/pkg/mod/github.com/inverse-inc/upnp@v0.0.0-20201222212413-bcc73e2a6122/GetListOfPortMappings.go:18 +0x4c
github.com/inverse-inc/upnp.(*Upnp).GetListOfPortMappings(...)
    /home/jeremy/go/pkg/mod/github.com/inverse-inc/upnp@v0.0.0-20201222212413-bcc73e2a6122/upnp.go:155
github.com/inverse-inc/wireguard-go/ztn.UPNPIGDCleanupMapped()
    /home/jeremy/Documents/git/wireguard-go/ztn/upnpigd.go:40 +0x20a
main.quit()
    /home/jeremy/Documents/git/wireguard-go/main_shared.go:261 +0x179
main.main()
    /home/jeremy/Documents/git/wireguard-go/main_linux.go:274 +0xa45
^C
```

**Comment by julsemaan** [comment]
Confirmed as OK by @jegoi and @fdurand
